### ISSUE TITLE
Use JAVAFX_HOME to locate java executable

### ISSUE THREAD

**Issue by delanym** [pmd/pmd-designer#86] opened 2024-05-21 06:16 UTC
Hi. I ran pmd v7.1.0 and was told missing JAVAFX_HOME.
I set the env var and ran it again and was told `No java executable found in PATH`
If pmd is going to depend on an env var for locating the JDK then it should search for Java from there, not the path.

**Comment by adangel** [comment] 2024-05-23 06:35
@delanym Please refer to https://docs.pmd-code.org/latest/pmd_userdocs_extending_designer_reference.html for how to setup JAVAFX_HOME.

Currently, we either support Oracle Java 8 (which includes javafx and predates java modules) or we support any OpenJDK without JavaFX + separate JavaFX (pointed to with JAVAFX_HOME).

The zulu builds of openjdk+javafx have integrated JavaFX as a module, which we don't support yet. I think, this is essentially the problem described in https://github.com/pmd/pmd-designer/issues/71 - which I'll rename now.


For your problem at hand: `java` is always used from the path (we don't use any special env var there). So make sure, your `PATH` contains the java version you want to use (either Java 8 or any Java-Only OpenJDK distribution will do). JavaFX (which is something different than Java) is searched from `JAVAFX_HOME` - you'll need to download that separately from https://gluonhq.com/products/javafx/ (the SDK variant), extract it somewhere and point `JAVAFX_HOME` to the directory.

E.g.

```
$ echo $JAVAFX_HOME
/home/andreas/programs/openjdk/javafx-sdk-17.0.8
$ ls $JAVAFX_HOME
legal  lib  src.zip
```


I'm closing this as a duplicate of #71.

**Closed by adangel** 2024-05-23 06:35 UTC

**Comment by delanym** [comment] 2024-05-23 09:29
Thanks. I get a warning `WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ce2b319'` but I can use it.
